framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto   # Or "true" if using HTTPS
        cookie_samesite: lax

# Optional if using ESI or fragments
# esi: true
# fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
