# config/packages/test/framework.yaml
framework:
    test: true

    session:
        enabled: true
        storage_factory_id: session.storage.factory.mock_file
        handler_id: null
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers:
        - 'x-forwarded-for'
        - 'x-forwarded-proto'
        - 'x-forwarded-host'
        - 'x-forwarded-port'
