name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/formmgmt:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            APP_SECRET=${{ secrets.APP_SECRET }}

            R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}
            R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }}
            R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }}
            R2_BUCKET=${{ secrets.R2_BUCKET }}
            R2_REGION=${{ secrets.R2_REGION }}
            R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }}

            SALESFORCE_TOKEN_URL=${{ secrets.SALESFORCE_TOKEN_URL }}
            SALESFORCE_CLIENT_ID=${{ secrets.SALESFORCE_CLIENT_ID }}
            SALESFORCE_CLIENT_SECRET=${{ secrets.SALESFORCE_CLIENT_SECRET }}
            SALESFORCE_INSTANCE_URL=${{ secrets.SALESFORCE_INSTANCE_URL }}

            DROPBOX_CLIENT_ID=${{ secrets.DROPBOX_CLIENT_ID }}
            DROPBOX_CLIENT_SECRET=${{ secrets.DROPBOX_CLIENT_SECRET }}
            DROPBOX_REFRESH_TOKEN=${{ secrets.DROPBOX_REFRESH_TOKEN }}

      - name: Logout from DockerHub
        run: docker logout
